/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    kotlin("jvm") version "2.2.0"
    application
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://maven.pkg.jetbrains.space/public/p/ktor/eap")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.openjfx.javafx.controls)
    api(libs.org.openjfx.javafx.fxml)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)
    api(libs.com.github.ajalt.clikt.clikt)
    api(libs.com.github.ajalt.clikt.clikt.markdown)
}

group = "com.FA"
version = "1.0-SNAPSHOT"
description = "Graphs"
java.sourceCompatibility = JavaVersion.VERSION_24

application {
    mainClass.set("com.fischerabruzese.graphvcli.MainKt")
}

javafx {
    version = "24"
    modules = listOf("javafx.controls", "javafx.fxml")
}

// Configure the shadow (fat) JAR
tasks.shadowJar {
    archiveBaseName.set("graphs-cli")
    archiveClassifier.set("")
    archiveVersion.set("")

    // Include JavaFX modules (since you're using JavaFX)
    mergeServiceFiles()

    manifest {
        attributes["Main-Class"] = "com.fischerabruzese.graphvcli.MainKt"
    }
}

tasks.jar {
    enabled = false
    dependsOn(tasks.shadowJar)
}

// Make sure shadowJar runs when building
tasks.build {
    dependsOn(tasks.shadowJar)
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
